FROM mirror.gcr.io/library/alpine:3.22
COPY deploy/local-livekit/run/olcrtc-linux /usr/local/bin/olcrtc
COPY deploy/local-livekit/run/local-livekit-helper-linux /usr/local/bin/local-livekit-helper
ENTRYPOINT []
